"use strict";

const path = require("node:path");
const {
	artifactFingerprint,
	sanitizeModuleName,
} = require("./contractArtifacts");
const { emitRemoteTypes, typeNameFor } = require("./luauTypeEmitter");
const { contractModel, manifestForContract } = require("./remoteContractModel");

const GENERATED_HEADER = "-- <auto-generated by luau-contract. Do not edit by hand.>";

function generatedHeader(kind, fingerprint) {
	return [
		"--!strict",
		GENERATED_HEADER,
		`-- luau-contract:${kind}:v1:${fingerprint}`,
		"",
	].join("\n");
}

function luaLiteral(value, indent = "") {
	if (value == null) {
		return "nil";
	}
	if (typeof value === "string") {
		return JSON.stringify(value);
	}
	if (typeof value === "number" || typeof value === "boolean") {
		return String(value);
	}
	if (Array.isArray(value)) {
		return `{ ${value.map((child) => luaLiteral(child, indent)).join(", ")} }`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value);
		if (entries.length === 0) {
			return "{}";
		}
		const childIndent = `${indent}\t`;
		const lines = ["{"];
		for (const [key, child] of entries) {
			const keyText = /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? key : `[${JSON.stringify(key)}]`;
			lines.push(`${childIndent}${keyText} = ${luaLiteral(child, childIndent)},`);
		}
		lines.push(`${indent}}`);
		return lines.join("\n");
	}
	return "nil";
}

function remoteField(remoteName) {
	return /^[A-Za-z_][A-Za-z0-9_]*$/.test(remoteName)
		? `remotes.${remoteName}`
		: `remotes[${JSON.stringify(remoteName)}]`;
}

function clientFunction(contract, remote) {
	const payloadType = typeNameFor(contract.name, remote.remoteName, "Payload");
	const responseType = typeNameFor(contract.name, remote.remoteName, "Response");

	if (!remote.clientCallable) {
		return null;
	}
	if (remote.transport === "function") {
		return [
			`function Client.${remote.remoteIdentifier}(remote: any, payload: ${payloadType}): ${responseType}?`,
			`\tassertRemoteFunction(remote, ${JSON.stringify(remote.remoteName)})`,
			"\treturn remote:InvokeServer(payload) :: any",
			"end",
		].join("\n");
	}
	return [
		`function Client.${remote.remoteIdentifier}(remote: any, payload: ${payloadType})`,
		`\tassertRemoteEvent(remote, ${JSON.stringify(remote.remoteName)})`,
		"\tremote:FireServer(payload)",
		"end",
	].join("\n");
}

function serverFireFunction(contract, remote) {
	const payloadType = typeNameFor(contract.name, remote.remoteName, "Payload");

	if (!remote.serverCanFire) {
		return null;
	}
	return [
		`function Server.fire${remote.remoteIdentifier}(remote: any, player: any, payload: ${payloadType})`,
		`\tassertClientRemote(remote, ${JSON.stringify(remote.remoteName)})`,
		"\tremote:FireClient(player, payload)",
		"end",
	].join("\n");
}

function runtimeImplementationLines(remote) {
	if (!remote.hasAction) {
		return [];
	}
	return [
		`\t\tlocal handler = handlerFor(handlers, ${JSON.stringify(remote.remoteName)}, ${JSON.stringify(remote.actionName)})`,
		"\t\tif handler ~= nil then",
		`\t\t\truntime:implement(${JSON.stringify(remote.actionName)}, handler, implementOptions)`,
		"\t\tend",
	];
}

function bindLine(remote) {
	const fieldName = remoteField(remote.remoteName);
	const remoteOptions = `bindOptions[${JSON.stringify(remote.remoteName)}] or bindOptions`;
	if (remote.hasAction) {
		return `\truntime:bindRemote(${JSON.stringify(remote.remoteName)}, ${fieldName}, ${remoteOptions})`;
	}
	return [
		"\tlocal legacyOptions = copyOptions(" + remoteOptions + ")",
		`\tlegacyOptions.handler = legacyOptions.handler or handlerFor(handlers, ${JSON.stringify(remote.remoteName)}, ${JSON.stringify(remote.actionName)})`,
		`\truntime:bindRemote(${JSON.stringify(remote.remoteName)}, ${fieldName}, legacyOptions)`,
	].join("\n");
}

function guardLine(remote) {
	const fieldName = remoteField(remote.remoteName);
	return [
		`\tconnections[${JSON.stringify(remote.remoteName)}] = Contracts.Roblox.RemoteGuard.connect(Contract, ${JSON.stringify(remote.remoteName)}, ${fieldName}, requireHandler(handlers, ${JSON.stringify(remote.remoteName)}, ${JSON.stringify(remote.actionName)}), guardOptions[${JSON.stringify(remote.remoteName)}] or guardOptions)`,
	].join("\n");
}

function generateClientModule(contract, options) {
	const model = contractModel(contract, options);
	const fingerprint = artifactFingerprint({
		kind: "remote-client",
		contract,
	});
	const functions = model.remotes
		.map((remote) => clientFunction(contract, remote))
		.filter(Boolean);
	const needsEventAssert = model.remotes.some((remote) => remote.clientCallable && remote.transport === "event");
	const needsFunctionAssert = model.remotes.some((remote) => remote.clientCallable && remote.transport === "function");
	const helperLines = [];
	if (needsEventAssert) {
		helperLines.push(
			"local function assertRemoteEvent(remote: any, remoteName: string)",
			"\tif remote == nil or type(remote.FireServer) ~= \"function\" then",
			"\t\terror(remoteName .. \" expects a RemoteEvent-like value with FireServer\", 3)",
			"\tend",
			"end",
			""
		);
	}
	if (needsFunctionAssert) {
		helperLines.push(
			"local function assertRemoteFunction(remote: any, remoteName: string)",
			"\tif remote == nil or type(remote.InvokeServer) ~= \"function\" then",
			"\t\terror(remoteName .. \" expects a RemoteFunction-like value with InvokeServer\", 3)",
			"\tend",
			"end",
			""
		);
	}

	const contents = [
		generatedHeader("remote-client", fingerprint),
		emitRemoteTypes(contract, options),
		"local Client = {}",
		"",
		...helperLines,
		functions.length > 0 ? functions.join("\n\n") : "-- No server-directed remotes are declared on this contract.",
		"",
		"return Client",
		"",
	].join("\n");

	return {
		path: path.join(options.outDir, `${model.clientModuleName}.luau`),
		contents,
	};
}

function generateServerModule(contract, options) {
	const model = contractModel(contract, options);
	const fingerprint = artifactFingerprint({
		kind: "remote-server",
		contract,
	});
	const fireFunctions = model.remotes
		.map((remote) => serverFireFunction(contract, remote))
		.filter(Boolean);
	const serverRemotes = model.remotes.filter((remote) => remote.serverBindable);
	const hasLegacyRemotes = serverRemotes.some((remote) => !remote.hasAction);
	const implementationLines = serverRemotes.flatMap(runtimeImplementationLines);
	const bindLines = serverRemotes.map(bindLine);
	const guardLines = serverRemotes.map(guardLine);
	const handlerChecks = serverRemotes.flatMap((remote) => [
		`\tif type(value[${JSON.stringify(remote.remoteName)}]) == "function" then`,
		"\t\treturn true",
		"\tend",
		`\tif type(value[${JSON.stringify(remote.actionName)}]) == "function" then`,
		"\t\treturn true",
		"\tend",
	]);

	const contents = [
		generatedHeader("remote-server", fingerprint),
		emitRemoteTypes(contract, options),
		"local Server = {}",
		"",
		...(hasLegacyRemotes ? [
		"local function copyOptions(options: any): any",
		"\tlocal copy = {}",
		"\tfor key, value in pairs(options or {}) do",
		"\t\tcopy[key] = value",
		"\tend",
		"\treturn copy",
		"end",
		"",
		] : []),
		"local function handlerFor(handlers: any?, remoteName: string, actionName: string): any?",
		"\tif type(handlers) ~= \"table\" then",
		"\t\treturn nil",
		"\tend",
		"\treturn handlers[remoteName] or handlers[actionName]",
		"end",
		"",
		"local function requireHandler(handlers: any?, remoteName: string, actionName: string): any",
		"\tlocal handler = handlerFor(handlers, remoteName, actionName)",
		"\tif type(handler) ~= \"function\" then",
		"\t\terror(remoteName .. \" needs a generated server handler\", 3)",
		"\tend",
		"\treturn handler",
		"end",
		"",
		"local function looksLikeHandlerMap(value: any): boolean",
		"\tif type(value) ~= \"table\" then",
		"\t\treturn false",
		"\tend",
		handlerChecks.length > 0 ? handlerChecks.join("\n") : "\treturn false",
		handlerChecks.length > 0 ? "\treturn false" : "",
		"end",
		"",
		...(fireFunctions.length > 0 ? [
		"local function assertClientRemote(remote: any, remoteName: string)",
		"\tif remote == nil or type(remote.FireClient) ~= \"function\" then",
		"\t\terror(remoteName .. \" expects a RemoteEvent-like value with FireClient\", 3)",
		"\tend",
		"end",
		"",
		] : []),
		"function Server.bind(runtime: any, remotes: {[string]: any}, handlersOrOptions: any?, options: any?)",
		"\tlocal handlers = if options ~= nil or looksLikeHandlerMap(handlersOrOptions) then handlersOrOptions else nil",
		"\tlocal bindOptions = if options ~= nil then options else if handlers ~= nil then {} else handlersOrOptions or {}",
		"\tlocal implementOptions = bindOptions.implementOptions or { overwrite = true }",
		implementationLines.length > 0 ? implementationLines.join("\n") : "\t-- No action implementations are generated for this contract.",
		bindLines.length > 0 ? bindLines.join("\n") : "\t-- No server-bindable remotes are declared on this contract.",
		"\treturn runtime",
		"end",
		"",
		"function Server.guard(Contracts: any, Contract: any, remotes: {[string]: any}, handlers: {[string]: any}, options: any?)",
		"\tlocal guardOptions = options or {}",
		"\tlocal connections = {}",
		guardLines.length > 0 ? guardLines.join("\n") : "\t-- No server-guardable remotes are declared on this contract.",
		"\treturn connections",
		"end",
		"",
		fireFunctions.length > 0 ? fireFunctions.join("\n\n") : "-- No client-directed remotes are declared on this contract.",
		"",
		"return Server",
		"",
	].join("\n");

	return {
		path: path.join(options.outDir, `${model.serverModuleName}.luau`),
		contents,
	};
}

function generateTypesModule(contract, options) {
	const model = contractModel(contract, options);
	const fingerprint = artifactFingerprint({
		kind: "remote-types",
		contract,
	});
	const contents = [
		generatedHeader("remote-types", fingerprint),
		emitRemoteTypes(contract, options),
		"return {}",
		"",
	].join("\n");

	return {
		path: path.join(options.outDir, `${model.typeModuleName}.luau`),
		contents,
	};
}

function generateManifestModule(contract, options) {
	const model = contractModel(contract, options);
	const fingerprint = artifactFingerprint({
		kind: "remote-manifest",
		contract,
	});
	const contents = [
		generatedHeader("remote-manifest", fingerprint),
		`return ${luaLiteral(manifestForContract(contract, options))}`,
		"",
	].join("\n");

	return {
		path: path.join(options.outDir, `${model.manifestModuleName}.luau`),
		contents,
	};
}

function generateRemoteWrapperFiles(artifacts, options = {}) {
	const outDir = path.resolve(options.outDir);
	const typeOptions = {
		attackConfig: options.attackConfig || {},
		customTypes: options.customTypes || {},
		vector3Type: options.vector3Type || "any",
	};
	const files = [];

	for (const contract of artifacts.contracts) {
		if (contract.remotes.length === 0) {
			continue;
		}
		files.push(generateTypesModule(contract, {
			...typeOptions,
			outDir,
		}));
		files.push(generateClientModule(contract, {
			...typeOptions,
			outDir,
		}));
		files.push(generateServerModule(contract, {
			...typeOptions,
			outDir,
		}));
		files.push(generateManifestModule(contract, {
			...typeOptions,
			outDir,
		}));
	}

	return files;
}

module.exports = {
	GENERATED_HEADER,
	generateRemoteWrapperFiles,
};
