"use strict";

const path = require("node:path");
const {
	artifactFingerprint,
	modulePathForRequire,
	sanitizeModuleName,
} = require("./contractArtifacts");
const { remoteAttackSummary } = require("./remoteContractModel");
const { testRemoteBlock } = require("./remoteAttackBlockRenderer");
const {
	luaLiteral,
	quote,
	validValue,
} = require("./remoteAttackValues");

function helperLinesFor(blocks) {
	const joinedBlocks = blocks.join("\n");
	const helperLines = [];
	if (joinedBlocks.includes("largeString(")) {
		helperLines.push(
			"local function largeString(length: number): string",
			"\treturn string.rep(\"A\", length)",
			"end",
			""
		);
	}
	if (joinedBlocks.includes("largeArray(")) {
		helperLines.push(
			"local function largeArray(length: number): {any}",
			"\tlocal values: {any} = {}",
			"\tfor index = 1, length do",
			"\t\tvalues[index] = index",
			"\tend",
			"\treturn values",
			"end",
			""
		);
	}
	if (joinedBlocks.includes("deepTable(")) {
		helperLines.push(
			"local function deepTable(depth: number): any",
			"\tlocal root: any = {}",
			"\tlocal cursor: any = root",
			"\tfor _ = 1, depth do",
			"\t\tlocal child = {}",
			"\t\tcursor.child = child",
			"\t\tcursor = child",
			"\tend",
			"\treturn root",
			"end",
			""
		);
	}
	return helperLines;
}

function generateSuite(contract, options) {
	const suitePath = path.join(options.outDir, `${sanitizeModuleName(contract.name, "RemoteAttackTests")}.luau`);
	const contractRequire = modulePathForRequire(suitePath, path.resolve(options.projectRoot, contract.path));
	const sdkRequire = options.sdkRequire || modulePathForRequire(suitePath, path.resolve(options.sdkRoot, "src/Contracts.lua"));
	const fingerprint = artifactFingerprint({
		kind: "remote-attack-tests",
		contract,
		attackConfig: options.attackConfig || {},
		contractRequire,
		sdkRequire,
	});

	const blocks = contract.remotes.map((remote) => testRemoteBlock(contract, remote, options.attackConfig || {}));
	const contents = [
		"--!strict",
		"-- <auto-generated by luau-contract. Do not edit by hand.>",
		`-- luau-contract:remote-attack-tests:v1:${fingerprint}`,
		"",
		`local Contracts = require(${quote(sdkRequire)})`,
		`local ContractModule = require(${quote(contractRequire)})`,
		"local Contract = ContractModule.Contract or ContractModule",
		"",
		...helperLinesFor(blocks),
		"return function(check)",
		blocks.map((block) => block.split("\n").map((line) => `\t${line}`).join("\n")).join("\n\n"),
		"end",
		"",
	].join("\n");

	return {
		path: suitePath,
		contents,
	};
}

function generateRunFile(contracts, options) {
	const suiteNames = contracts
		.filter((contract) => contract.remotes.length > 0)
		.map((contract) => sanitizeModuleName(contract.name, "RemoteAttackTests"));
	const lines = [
		"--!strict",
		"-- <auto-generated by luau-contract. Do not edit by hand.>",
		"",
		"local suites: {((any) -> ())} = {",
		...suiteNames.map((name) => `\trequire(${quote(`./${name}`)}) :: any,`),
		"}",
		"",
		"local passed = 0",
		"local failed = 0",
		"",
		"local function check(name: string, condition: boolean)",
		"\tif condition then",
		"\t\tpassed += 1",
		"\telse",
		"\t\tfailed += 1",
		"\t\tprint(\"FAIL: \" .. name)",
		"\tend",
		"end",
		"",
		"for _, suite in ipairs(suites) do",
		"\tsuite(check)",
		"end",
		"",
		"print((\"%d generated remote attack checks passed, %d failed\"):format(passed, failed))",
		"if failed > 0 then",
		"\terror(\"generated remote attack checks failed\", 2)",
		"end",
		"",
	];

	return {
		path: path.join(options.outDir, "run.luau"),
		contents: lines.join("\n"),
	};
}

function generateRemoteAttackTestFiles(artifacts, options = {}) {
	const outDir = path.resolve(options.outDir);
	const contracts = artifacts.contracts.filter((contract) => contract.remotes.length > 0 && contract.path);
	const files = contracts.map((contract) => generateSuite(contract, {
		...options,
		outDir,
	}));
	if (files.length > 0) {
		files.push(generateRunFile(contracts, {
			...options,
			outDir,
		}));
	}
	return files;
}

module.exports = {
	attackCaseSummary: remoteAttackSummary,
	generateRemoteAttackTestFiles,
	luaLiteral,
	validValue,
};
