"use strict";

const GENERATED_HEADER = "-- <auto-generated by luau-contract. Do not edit by hand.>";

function generatedHeader(kind, fingerprint) {
	return [
		"--!strict",
		GENERATED_HEADER,
		`-- luau-contract:${kind}:v1:${fingerprint}`,
		"",
	].join("\n");
}

module.exports = {
	GENERATED_HEADER,
	generatedHeader,
};
