"use strict";

const path = require("node:path");
const {
	artifactFingerprint,
	sanitizeIdentifier,
	sanitizeModuleName,
} = require("./contractArtifacts");
const { emitRemoteTypes, typeNameFor } = require("./luauTypeEmitter");

const GENERATED_HEADER = "-- <auto-generated by luau-contract. Do not edit by hand.>";

function generatedHeader(kind, fingerprint) {
	return [
		"--!strict",
		GENERATED_HEADER,
		`-- luau-contract:${kind}:v1:${fingerprint}`,
		"",
	].join("\n");
}

function clientFunction(contract, remote) {
	const functionName = sanitizeIdentifier(remote.remoteName);
	const payloadType = typeNameFor(contract.name, remote.remoteName, "Payload");
	const responseType = typeNameFor(contract.name, remote.remoteName, "Response");

	if (remote.direction === "client") {
		return null;
	}
	if (remote.response != null) {
		return [
			`function Client.${functionName}(remote: any, payload: ${payloadType}): ${responseType}?`,
			"\treturn remote:InvokeServer(payload) :: any",
			"end",
		].join("\n");
	}

	return [
		`function Client.${functionName}(remote: any, payload: ${payloadType})`,
		"\tremote:FireServer(payload)",
		"end",
	].join("\n");
}

function serverFireFunction(contract, remote) {
	const functionName = sanitizeIdentifier(remote.remoteName);
	const payloadType = typeNameFor(contract.name, remote.remoteName, "Payload");

	if (remote.direction !== "client" && remote.direction !== "bidirectional") {
		return null;
	}

	return [
		`function Server.fire${functionName}(remote: any, player: any, payload: ${payloadType})`,
		"\tremote:FireClient(player, payload)",
		"end",
	].join("\n");
}

function bindLine(remote) {
	const remoteName = remote.remoteName;
	const fieldName = /^[A-Za-z_][A-Za-z0-9_]*$/.test(remoteName)
		? `remotes.${remoteName}`
		: `remotes[${JSON.stringify(remoteName)}]`;
	return `\truntime:bindRemote(${JSON.stringify(remoteName)}, ${fieldName}, bindOptions[${JSON.stringify(remoteName)}] or bindOptions)`;
}

function generateClientModule(contract, options) {
	const fingerprint = artifactFingerprint({
		kind: "remote-client",
		contract,
	});
	const functions = contract.remotes
		.map((remote) => clientFunction(contract, remote))
		.filter(Boolean);

	const contents = [
		generatedHeader("remote-client", fingerprint),
		emitRemoteTypes(contract, options),
		"local Client = {}",
		"",
		functions.length > 0 ? functions.join("\n\n") : "-- No server-directed remotes are declared on this contract.",
		"",
		"return Client",
		"",
	].join("\n");

	return {
		path: path.join(options.outDir, `${sanitizeModuleName(contract.name, "Client")}.luau`),
		contents,
	};
}

function generateServerModule(contract, options) {
	const fingerprint = artifactFingerprint({
		kind: "remote-server",
		contract,
	});
	const fireFunctions = contract.remotes
		.map((remote) => serverFireFunction(contract, remote))
		.filter(Boolean);
	const bindLines = contract.remotes
		.filter((remote) => remote.direction !== "client")
		.map(bindLine);

	const contents = [
		generatedHeader("remote-server", fingerprint),
		emitRemoteTypes(contract, options),
		"local Server = {}",
		"",
		"function Server.bind(runtime: any, remotes: {[string]: any}, options: any?)",
		"\tlocal bindOptions = options or {}",
		bindLines.length > 0 ? bindLines.join("\n") : "\t-- No server-bindable remotes are declared on this contract.",
		"\treturn runtime",
		"end",
		"",
		fireFunctions.length > 0 ? fireFunctions.join("\n\n") : "-- No client-directed remotes are declared on this contract.",
		"",
		"return Server",
		"",
	].join("\n");

	return {
		path: path.join(options.outDir, `${sanitizeModuleName(contract.name, "Server")}.luau`),
		contents,
	};
}

function generateTypesModule(contract, options) {
	const fingerprint = artifactFingerprint({
		kind: "remote-types",
		contract,
	});
	const contents = [
		generatedHeader("remote-types", fingerprint),
		emitRemoteTypes(contract, options),
		"return {}",
		"",
	].join("\n");

	return {
		path: path.join(options.outDir, `${sanitizeModuleName(contract.name, "Types")}.luau`),
		contents,
	};
}

function generateRemoteWrapperFiles(artifacts, options = {}) {
	const outDir = path.resolve(options.outDir);
	const typeOptions = {
		customTypes: options.customTypes || {},
		vector3Type: options.vector3Type || "any",
	};
	const files = [];

	for (const contract of artifacts.contracts) {
		if (contract.remotes.length === 0) {
			continue;
		}
		files.push(generateTypesModule(contract, {
			...typeOptions,
			outDir,
		}));
		files.push(generateClientModule(contract, {
			...typeOptions,
			outDir,
		}));
		files.push(generateServerModule(contract, {
			...typeOptions,
			outDir,
		}));
	}

	return files;
}

module.exports = {
	GENERATED_HEADER,
	generateRemoteWrapperFiles,
};
