"use strict";

const fs = require("node:fs");
const path = require("node:path");

const DEFAULT_SDK_REQUIRE = "../src/Contracts";

// Generated templates use plain JS template strings (no dependency on the
// generator's luaLiteral module). This local sanitizer keeps user-supplied
// system/action names safe to drop into Luau identifiers and string literals.
function sanitizeIdentifier(value, fallback) {
	const cleaned = String(value || "").replace(/[^A-Za-z0-9_]/g, "");
	if (cleaned === "" || /^[0-9]/.test(cleaned)) {
		return fallback;
	}
	return cleaned;
}

function luaString(value) {
	return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;
}

function normalizeActions(actions) {
	const seen = new Set();
	const normalized = [];
	for (const raw of actions || []) {
		const name = sanitizeIdentifier(raw, "");
		if (name === "" || seen.has(name)) {
			continue;
		}
		seen.add(name);
		normalized.push(name);
	}
	return normalized;
}

function remoteDirection(remoteKind) {
	// Both event and function remotes are server-directed; a "function" remote
	// declares a response schema while an "event" remote does not.
	return remoteKind === "function" ? "function" : "event";
}

function contractTemplate(systemName, actions, sdkRequire, remoteKind) {
	const wantsResponse = remoteDirection(remoteKind) === "function";
	// Each action is declared with :action(...) so it is both implementable on the
	// runtime and bindable as a validated remote (an embedded remote = {...} block).
	const actionBlocks = actions.map((action) => {
		const responseLine = wantsResponse
			? "\n\t\t\t-- TODO: replace with the real response shape this remote returns.\n"
				+ "\t\t\tresponse = Contracts.object({\n"
				+ "\t\t\t\tok = Contracts.boolean(),\n"
				+ "\t\t\t}, {\n"
				+ "\t\t\t\tallowExtra = false,\n"
				+ "\t\t\t}),"
			: "";
		return `\t:action(${luaString(action)}, {
\t\t-- TODO: describe the validated request payload for ${action}.
\t\tinput = Contracts.object({
\t\t\tExampleId = Contracts.stringId(),
\t\t}, {
\t\t\tallowExtra = false,
\t\t}),
\t\t-- TODO: describe the validated handler return value for ${action}.
\t\toutput = Contracts.object({
\t\t\tok = Contracts.boolean(),
\t\t}, {
\t\t\tallowExtra = false,
\t\t}),
\t\t-- TODO: list the state paths this action is allowed to write.
\t\twrites = { "Player.Path" },
\t\tremote = {
\t\t\tname = ${luaString(action)},
\t\t\tdirection = "server",
\t\t\t-- TODO: require the "player" actor policy declared above, or remove for an open remote.
\t\t\tactor = "player",${responseLine}
\t\t\t-- TODO: tune the per-caller rate limit (or remove to leave the remote unmetered).
\t\t\trateLimit = {
\t\t\t\tmaxRequests = 10,
\t\t\t\twindowSeconds = 1,
\t\t\t},
\t\t},
\t})`;
	}).join("\n");

	return `--!strict
-- Contract definition for the ${systemName} system.
-- Generated by \`luau-contract scaffold\`; replace the TODO placeholders below.

local Contracts = require(${luaString(sdkRequire)})

return Contracts.system(${luaString(systemName)})
\t-- TODO: implement the real authorization check for this actor policy.
\t:actorPolicy("player", function(player)
\t\treturn player ~= nil or "a player is required"
\tend)
\t-- TODO: declare the state paths this system may write before using them above.
\t:mayWrite("Player.Path")
${actionBlocks}
`;
}

function runtimeTemplate(systemName, actions, sdkRequire, contractRequire) {
	const implementBlocks = actions.map((action) => {
		return `runtime:implement(${luaString(action)}, function(scope: any)
\t-- Transactional (default): staged, applied on commit, undone on rollback.
\tscope:write("Player.Path", {
\t\tcommit = function(context) --[[ TODO: apply the ${action} effect ]] end,
\t\trollback = function(context) --[[ TODO: undo the ${action} effect ]] end,
\t})
\t-- scope:writeEager(path, valueOrWriter) runs immediately and cannot be rolled back.
\t-- TODO: return the validated response for ${action}.
\treturn { ok = true }
end)`;
	}).join("\n\n");

	const remoteEntries = actions.map((action) => {
		return `\t-- ${action} = ReplicatedStorage.Remotes.${action},`;
	}).join("\n");

	return `--!strict
-- Runtime bindings for the ${systemName} system.
-- Generated by \`luau-contract scaffold\`; replace the TODO placeholders below.

local Contracts = require(${luaString(sdkRequire)})
local contract = require(${luaString(contractRequire)})

local runtime = Contracts.runtime(contract)

${implementBlocks}

-- Bind the validated remotes to the runtime. Replace the placeholders with the
-- real RemoteEvent/RemoteFunction instances (e.g. children of a Remotes folder).
-- TODO: resolve the remote instances this system owns.
local remotes = {
${remoteEntries}
}
runtime:bindRemotes(remotes)

return runtime
`;
}

function testTemplate(systemName, actions, sdkRequire, contractRequire) {
	const callBlocks = actions.map((action) => {
		return `\t\t-- TODO: return the real ${action} response your handler produces.
\t\tharness:implement(${luaString(action)}, function(scope: any)
\t\t\treturn { ok = true }
\t\tend)
\t\tharness:bind(${luaString(action)})

\t\tlocal ${action}Result = harness:call(${luaString(action)}, player, {
\t\t\t-- TODO: supply a valid ${action} payload.
\t\t\tExampleId = "example",
\t\t})
\t\t-- TODO: assert on the real ${action} response shape.
\t\tcheck("${action} happy path returns a response", ${action}Result ~= nil)`;
	}).join("\n\n");

	return `--!strict
-- RemoteHarness tests for the ${systemName} system.
-- Generated by \`luau-contract scaffold\`; replace the TODO assertions below.

local Contracts = require(${luaString(sdkRequire)})
local contract = require(${luaString(contractRequire)})

return function(test)
\tlocal function check(name, condition)
\t\ttest:check(name, condition)
\tend

\ttest:section(${luaString(systemName)})

\tdo
\t\tlocal harness = Contracts.Test.remoteHarness(contract)
\t\tlocal player = { UserId = 1, Name = "Player" }

${callBlocks}
\tend
end
`;
}

function requireFromTo(fromFile, toModule) {
	// Build a relative Luau require path (without extension) from one generated
	// file to another, always prefixed with "./" or "../".
	const relative = path.relative(path.dirname(fromFile), toModule).replace(/\\/g, "/");
	const stripped = relative.replace(/\.luau?$/, "");
	return stripped.startsWith(".") ? stripped : `./${stripped}`;
}

function emitFile(filePath, contents, force) {
	if (fs.existsSync(filePath) && !force) {
		throw new Error(`refusing to overwrite ${filePath}; pass --force to replace it`);
	}
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, contents.endsWith("\n") ? contents : `${contents}\n`);
	return filePath;
}

// Core scaffolder shared by the scaffold and init commands. Writes the contract,
// runtime, and test stubs and returns the absolute paths it created.
function scaffoldSystem(config) {
	const systemName = sanitizeIdentifier(config.system, "");
	if (systemName === "") {
		throw new Error("scaffold requires --system <Name> (letters, digits, underscores)");
	}
	const actions = normalizeActions(config.actions);
	if (actions.length === 0) {
		throw new Error("scaffold requires --actions <A,B,C> with at least one action name");
	}

	const outDir = path.resolve(config.outDir);
	const testsDir = config.testsOutDir ? path.resolve(config.testsOutDir) : outDir;
	const sdkRequire = config.sdkRequire || DEFAULT_SDK_REQUIRE;
	const remoteKind = config.remoteKind || null;

	const contractPath = path.join(outDir, `${systemName}.contract.lua`);
	const runtimePath = path.join(outDir, `${systemName}Runtime.server.lua`);
	const testPath = path.join(testsDir, `${systemName}.test.lua`);

	const contractRequireForRuntime = requireFromTo(runtimePath, path.join(outDir, `${systemName}.contract`));
	const contractRequireForTest = requireFromTo(testPath, path.join(outDir, `${systemName}.contract`));
	const sdkRequireForTest = sdkRequire;

	const created = [];
	created.push(emitFile(contractPath, contractTemplate(systemName, actions, sdkRequire, remoteKind), config.force));
	created.push(emitFile(runtimePath, runtimeTemplate(systemName, actions, sdkRequire, contractRequireForRuntime), config.force));
	created.push(emitFile(testPath, testTemplate(systemName, actions, sdkRequireForTest, contractRequireForTest), config.force));

	return {
		systemName,
		actions,
		files: created,
		contractPath,
		runtimePath,
		testPath,
	};
}

function printCreated(files) {
	process.stdout.write("Created:\n");
	for (const filePath of files) {
		process.stdout.write(`  ${filePath}\n`);
	}
}

function printScaffoldNextSteps(result) {
	process.stdout.write(`\nNext steps:
  1. Replace the TODO schemas, actor policy, and rate limits in ${result.systemName}.contract.lua.
  2. Implement each runtime handler in ${result.systemName}Runtime.server.lua (use scope:write with commit/rollback for transactional effects).
  3. Run \`npm run scan\` (or \`node tools/luau-contract.js scan\`) to type-check the contract.
  4. Generate strict remote wrappers: \`node tools/luau-contract.js generate remotes --contract-module ${result.systemName}.contract.lua\`.
  5. Fill in the assertions in ${result.systemName}.test.lua and run your Luau test suite.
`);
}

async function runScaffold(options) {
	if (!options.out) {
		throw new Error("scaffold requires --out <dir> for the generated files");
	}
	const result = scaffoldSystem({
		system: options.system,
		actions: options.actions,
		outDir: options.out,
		testsOutDir: options.testsOut,
		sdkRequire: options.sdkRequire,
		remoteKind: options.remoteKind,
		force: options.force,
	});

	printCreated(result.files);
	printScaffoldNextSteps(result);
	return 0;
}

module.exports = {
	DEFAULT_SDK_REQUIRE,
	runScaffold,
	sanitizeIdentifier,
	scaffoldSystem,
};
